[mypy]
python_version = 3.14
ignore_missing_imports = True
strict = False
warn_unused_configs = True
exclude = /(?:\.venv|venv|build|dist|__pycache__|\.mypy_cache)/
files = backend/src, frontend/src, telegram/src
follow_imports = silent
show_error_codes = True
